# Generated by Django 4.2.17 on 2025-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
