# Generated by Django 4.2.17 on 2025-01-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_challenge2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='challenge2',
        ),
    ]
