# Generated by Django 4.2.17 on 2025-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_challenge_remove_comment_challenge2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.CharField(default='xx', max_length=255),
        ),
    ]
