# Generated by Django 4.2.17 on 2025-01-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='challenge',
        ),
    ]
